description: Runs create-typescript-app in transition mode

name: Transition

runs:
  steps:
    - uses: ./.github/actions/prepare
    - run: npx create-typescript-app
      shell: bash
    - id: auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
      with:
        commit_author: The Friendly Bingo Bot <bot@create.bingo>
        commit_message: Check in changes from re-running npx create-typescript-app
        commit_user_email: bot@create.bingo
        commit_user_name: The Friendly Bingo Bot
    - id: engines-changed
      name: Check if engines field changed
      run: |
        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        BEFORE_ENGINES=$(git show "$BASE_SHA:package.json" | jq '.engines')
        AFTER_ENGINES=$(cat package.json | jq '.engines')
        if [ "$BEFORE_ENGINES" != "$AFTER_ENGINES" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - if: steps.auto-commit-action.outputs.changes_detected == 'true'
      uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
      with:
        issue: ${{ github.event.pull_request.number }}
        message: |-
          🤖 Beep boop! I ran `npx create-typescript-app` and it updated some files.

          I went ahead and checked those changes into this PR for you. Please review the latest commit to see if you want to merge it.

          Cheers!
           — _The Friendly Bingo Bot_ 💝

          > ℹ️ These automatic commits keep your repository up-to-date with new versions of [create-typescript-app](https://github.com/JoshuaKGoldberg/create-typescript-app). If you want to opt out, delete your `.github/workflows/cta-transitions.yml` file.
    - if: steps.engines-changed.outputs.changed == 'true'
      name: Change PR to draft and note the breaking engines change
      run: |
        gh pr edit --body ""
      shell: bash
    - name: Add ENGINES_INDICATOR to PR body if missing
      if: steps.engines-changed.outputs.changed == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr ready --undo
        CURRENT_BODY=$(gh pr view --json body)
        ENGINES_INDICATOR="Note: This PR has a breaking change to the `engines` field in `package.json`. It is now a draft PR until you update the PR body to indicate that you are ready to merge it."
        if ! grep -qF "$ENGINES_INDICATOR" <<< "$CURRENT_BODY"; then
          gh pr edit "$PR_NUMBER" --body "$CURRENT_BODY\n\n$ENGINES_INDICATOR"
        fi
  using: composite
