description: Runs create-typescript-app in transition mode

name: Transition

runs:
  steps:
    - uses: ./.github/actions/prepare
    - id: auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
      with:
        commit_author: The Friendly Bingo Bot <bot@create.bingo>
        commit_message: Check in changes from re-running npx create-typescript-app
        commit_user_email: bot@create.bingo
        commit_user_name: The Friendly Bingo Bot
    - id: engines-changed
      name: Check if engines field changed
      run: |
        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        BASE_ENGINES=$(git show "$BASE_SHA:package.json" | jq '.engines')
        PR_ENGINES=$(cat package.json | jq '.engines')
        if [ "$BASE_ENGINES" != "$PR_ENGINES" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        echo "BASE engines: $BASE_ENGINES"
        echo "PR engines: $PR_ENGINES"
      shell: bash
    - env:
        GITHUB_TOKEN: ${{ inputs.token }}
      if: steps.engines-changed.outputs.changed == 'true'
      name: Set PR to draft and mention the change its body
      run: |
        gh pr ready --undo
        CURRENT_BODY=$(gh pr view --json body)
        ENGINES_INDICATOR="Note: This PR has a breaking change to the `engines` field in `package.json`. It is now a draft PR until you update the PR body to indicate that you are ready to merge it."
        if ! grep -qF "$ENGINES_INDICATOR" <<< "$CURRENT_BODY"; then
          gh pr edit "$PR_NUMBER" --body "$CURRENT_BODY\n\n$ENGINES_INDICATOR"
        fi
      shell: bash
  using: composite
