jobs:
  transition:
    name: Transition
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        if: contains(github.event.pull_request.title, 'testing engine changes')
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.ACCESS_TOKEN }}
      - if: steps.checkout.outcome != 'skipped'
        uses: ./.github/actions/transition

name: CTA

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
